distribute-on:
  default: 1 linux-small

assignment-rules:
  - projects:
    - "*"
    run-on:
      - agent: "linux-small"
        parallelism: 3

distribution-rules:
  - projects:
      - "*"
    arguments:
      parallel: false
    flaky-retry-config:
      enabled: true
